server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:miniewallet}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:walletuser}
    password: ${POSTGRES_PASSWORD:walletpass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:j02qK8DlZPd4RmSHXkSAyYb5pxQyJ5fkqMTiMVn8ceCXjLma8HXWQIX2tHXk2A/G}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  stripe:
    secret-key: ${STRIPE_SECRET_KEY:}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
    success-url: ${STRIPE_SUCCESS_URL:http://localhost:5173/topup?checkout=success}
    cancel-url: ${STRIPE_CANCEL_URL:http://localhost:5173/topup?checkout=cancel}

logging:
  level:
    root: INFO
    org.springframework: INFO
